
YAHOO.Tools=function(){keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";regExs={quotes:/\x22/g,startspace:/^\s+/g,endspace:/\s+$/g,striptags:/<\/?[^>]+>/gi,hasbr:/<br/i,hasp:/<p>/i,rbr:/<br>/gi,rbr2:/<br\/>/gi,rendp:/<\/p>/gi,rp:/<p>/gi,base64:/[^A-Za-z0-9\+\/\=]/g}
return{version:'0.8'}}();YAHOO.Tools.getHeight=function(elm){var elm=$(elm);var h=$D.getStyle(elm,'height');if(h=='auto'){elm.style.zoom=1;h=elm.clientHeight+'px';}
return h;}
YAHOO.Tools.getCenter=function(elm){var elm=$(elm);var cX=Math.round(($D.getViewportWidth()-parseInt($D.getStyle(elm,'width')))/2);var cY=Math.round(($D.getViewportHeight()-parseInt(this.getHeight(elm)))/2);return[cX,cY];}
YAHOO.Tools.makeTextObject=function(txt){return document.createTextNode(txt);}
YAHOO.Tools.makeChildren=function(arr,elm){var elm=$(elm);for(var i in arr){_val=arr[i];if(typeof _val=='string'){_val=this.makeTxtObject(_val);}
elm.appendChild(_val);}}
YAHOO.Tools.styleToCamel=function(str){var _tmp=str.split('-');var _new_style=_tmp[0];for(var i=1;i<_tmp.length;i++){_new_style+=_tmp[i].substring(0,1).toUpperCase()+_tmp[i].substring(1,_tmp[i].length);}
return _new_style;}
YAHOO.Tools.removeQuotes=function(str){var checkText=new String(str);return String(checkText.replace(regExs.quotes,''));}
YAHOO.Tools.trim=function(str){return str.replace(regExs.startspace,'').replace(regExs.endspace,'');}
YAHOO.Tools.stripTags=function(str){return str.replace(regExs.striptags,'');}
YAHOO.Tools.hasBRs=function(str){return str.match(regExs.hasbr)||str.match(regExs.hasp);}
YAHOO.Tools.convertBRs2NLs=function(str){return str.replace(regExs.rbr,"\n").replace(regExs.rbr2,"\n").replace(regExs.rendp,"\n").replace(regExs.rp,"");}
YAHOO.Tools.stringRepeat=function(str,repeat){return new Array(repeat+1).join(str);}
YAHOO.Tools.stringReverse=function(str){var new_str='';for(i=0;i<str.length;i++){new_str=new_str+str.charAt((str.length-1)-i);}
return new_str;}
YAHOO.Tools.printf=function(){var num=arguments.length;var oStr=arguments[0];for(var i=1;i<num;i++){var pattern="\\{"+(i-1)+"\\}";var re=new RegExp(pattern,"g");oStr=oStr.replace(re,arguments[i]);}
return oStr;}
YAHOO.Tools.setStyleString=function(el,str){var _tmp=str.split(';');for(x in _tmp){if(x){__tmp=YAHOO.Tools.trim(_tmp[x]);__tmp=_tmp[x].split(':');if(__tmp[0]&&__tmp[1]){var _attr=YAHOO.Tools.trim(__tmp[0]);var _val=YAHOO.Tools.trim(__tmp[1]);if(_attr&&_val){if(_attr.indexOf('-')!=-1){_attr=YAHOO.Tools.styleToCamel(_attr);}
$D.setStyle(el,_attr,_val);}}}}}
YAHOO.Tools.getSelection=function(_document,_window){if(!_document){_document=document;}
if(!_window){_window=window;}
if(_document.selection){return _document.selection;}
return _window.getSelection();}
YAHOO.Tools.removeElement=function(el){if(!(el instanceof Array)){el=new Array($(el));}
for(var i=0;i<el.length;i++){if(el[i].parentNode){el[i].parentNode.removeChild(el);}}}
YAHOO.Tools.setCookie=function(name,value,expires,path,domain,secure){var argv=arguments;var argc=arguments.length;var expires=(argc>2)?argv[2]:null;var path=(argc>3)?argv[3]:'/';var domain=(argc>4)?argv[4]:null;var secure=(argc>5)?argv[5]:false;document.cookie=name+"="+escape(value)+
((expires==null)?"":("; expires="+expires.toGMTString()))+
((path==null)?"":("; path="+path))+
((domain==null)?"":("; domain="+domain))+
((secure==true)?"; secure":"");}
YAHOO.Tools.getCookie=function(name){var dc=document.cookie;var prefix=name+'=';var begin=dc.indexOf('; '+prefix);if(begin==-1){begin=dc.indexOf(prefix);if(begin!=0)return null;}else{begin+=2;}
var end=document.cookie.indexOf(';',begin);if(end==-1){end=dc.length;}
return unescape(dc.substring(begin+prefix.length,end));}
YAHOO.Tools.deleteCookie=function(name,path,domain){if(getCookie(name)){document.cookie=name+'='+((path)?'; path='+path:'')+((domain)?'; domain='+domain:'')+'; expires=Thu, 01-Jan-70 00:00:01 GMT';}}
YAHOO.Tools.getBrowserEngine=function(){var opera=((window.opera&&window.opera.version)?true:false);var safari=((navigator.vendor&&navigator.vendor.indexOf('Apple')!=-1)?true:false);var gecko=((document.getElementById&&!document.all&&!opera&&!safari)?true:false);var msie=((window.ActiveXObject)?true:false);var version=false;if(msie){if(typeof document.body.style.maxHeight!="undefined"){version='7';}else{version='6';}}
if(opera){var tmp_version=window.opera.version().split('.');version=tmp_version[0]+'.'+tmp_version[1];}
if(gecko){if(navigator.registerContentHandler){version='2';}else{version='1.5';}
if((navigator.vendorSub)&&!version){version=navigator.vendorSub;}}
if(safari){try{if(console){if((window.onmousewheel!=='undefined')&&(window.onmousewheel===null)){version='2';}else{version='1.3';}}}catch(e){version='1.2';}}
var browsers={ua:navigator.userAgent,opera:opera,safari:safari,gecko:gecko,msie:msie,version:version}
return browsers;}
YAHOO.Tools.getBrowserAgent=function(){var ua=navigator.userAgent.toLowerCase();var opera=((ua.indexOf('opera')!=-1)?true:false);var safari=((ua.indexOf('safari')!=-1)?true:false);var firefox=((ua.indexOf('firefox')!=-1)?true:false);var msie=((ua.indexOf('msie')!=-1)?true:false);var mac=((ua.indexOf('mac')!=-1)?true:false);var unix=((ua.indexOf('x11')!=-1)?true:false);var win=((mac||unix)?false:true);var version=false;var mozilla=false;var flash=this.checkFlash();if(!firefox&&!safari&&(ua.indexOf('gecko')!=-1)){mozilla=true;var _tmp=ua.split('/');version=_tmp[_tmp.length-1].split(' ')[0];}
if(firefox){var _tmp=ua.split('/');version=_tmp[_tmp.length-1].split(' ')[0];}
if(msie){version=ua.substring((ua.indexOf('msie ')+5)).split(';')[0];}
if(safari){version=this.getBrowserEngine().version;}
if(opera){version=ua.substring((ua.indexOf('opera/')+6)).split(' ')[0];}
var browsers={ua:navigator.userAgent,opera:opera,safari:safari,firefox:firefox,mozilla:mozilla,msie:msie,mac:mac,win:win,unix:unix,version:version,flash:flash}
return browsers;}
YAHOO.Tools.checkFlash=function(){var flashObj=null;var tokens,len,curr_tok;if(navigator.mimeTypes&&navigator.mimeTypes['application/x-shockwave-flash']){flashObj=navigator.mimeTypes['application/x-shockwave-flash'].enabledPlugin;}
if(flashObj==null){flash=false;}else{tokens=navigator.plugins['Shockwave Flash'].description.split(' ');len=tokens.length;while(len--){curr_tok=tokens[len];if(!isNaN(parseInt(curr_tok))){hasVersion=curr_tok;flash=hasVersion;break;}}}
return flash;}
YAHOO.Tools.setAttr=function(attrsObj,elm){if(typeof elm=='string'){elm=$(elm);}
for(var i in attrsObj){switch(i.toLowerCase()){case'listener':if(attrsObj[i]instanceof Array){var ev=attrsObj[i][0];var func=attrsObj[i][1];var base=attrsObj[i][2];var scope=attrsObj[i][3];$E.addListener(elm,ev,func,base,scope);}
break;case'classname':case'class':elm.className=attrsObj[i];break;case'style':YAHOO.Tools.setStyleString(elm,attrsObj[i]);break;default:elm.setAttribute(i,attrsObj[i]);break;}}}
YAHOO.Tools.create=function(tagName){tagName=tagName.toLowerCase();elm=document.createElement(tagName);var txt=false;var attrsObj=false;if(!elm){return false;}
for(var i=1;i<arguments.length;i++){txt=arguments[i];if(typeof txt=='string'){_txt=YAHOO.Tools.makeTextObject(txt);elm.appendChild(_txt);}else if(txt instanceof Array){YAHOO.Tools.makeChildren(txt,elm);}else if(typeof txt=='object'){YAHOO.Tools.setAttr(txt,elm);}}
return elm;}
YAHOO.Tools.insertAfter=function(elm,curNode){if(curNode.nextSibling){curNode.parentNode.insertBefore(elm,curNode.nextSibling);}else{curNode.parentNode.appendChild(elm);}}
YAHOO.Tools.inArray=function(arr,val){if(arr instanceof Array){for(var i=(arr.length-1);i>=0;i--){if(arr[i]===val){return true;}}}
return false;}
YAHOO.Tools.checkBoolean=function(str){return((typeof str=='boolean')?true:false);}
YAHOO.Tools.checkNumber=function(str){return((isNaN(str))?false:true);}
YAHOO.Tools.PixelToEm=function(size){var data={};var sSize=(size/13);data.other=(Math.round(sSize*100)/100);data.msie=(Math.round((sSize*0.9759)*100)/100);return data;}
YAHOO.Tools.PixelToEmStyle=function(size,prop){var data='';var prop=((prop)?prop.toLowerCase():'width');var sSize=(size/13);data+=prop+':'+(Math.round(sSize*100)/100)+'em;';data+='*'+prop+':'+(Math.round((sSize*0.9759)*100)/100)+'em;';if((prop=='width')||(prop=='height')){data+='min-'+prop+':'+size+'px;';}
return data;}
YAHOO.Tools.base64Encode=function(str){var data="";var chr1,chr2,chr3,enc1,enc2,enc3,enc4;var i=0;do{chr1=str.charCodeAt(i++);chr2=str.charCodeAt(i++);chr3=str.charCodeAt(i++);enc1=chr1>>2;enc2=((chr1&3)<<4)|(chr2>>4);enc3=((chr2&15)<<2)|(chr3>>6);enc4=chr3&63;if(isNaN(chr2)){enc3=enc4=64;}else if(isNaN(chr3)){enc4=64;}
data=data+keyStr.charAt(enc1)+keyStr.charAt(enc2)+keyStr.charAt(enc3)+keyStr.charAt(enc4);}while(i<str.length);return data;}
YAHOO.Tools.base64Decode=function(str){var data="";var chr1,chr2,chr3,enc1,enc2,enc3,enc4;var i=0;str=str.replace(regExs.base64,"");do{enc1=keyStr.indexOf(str.charAt(i++));enc2=keyStr.indexOf(str.charAt(i++));enc3=keyStr.indexOf(str.charAt(i++));enc4=keyStr.indexOf(str.charAt(i++));chr1=(enc1<<2)|(enc2>>4);chr2=((enc2&15)<<4)|(enc3>>2);chr3=((enc3&3)<<6)|enc4;data=data+String.fromCharCode(chr1);if(enc3!=64){data=data+String.fromCharCode(chr2);}
if(enc4!=64){data=data+String.fromCharCode(chr3);}}while(i<str.length);return data;}
YAHOO.Tools.getQueryString=function(str){if(!str){var str=location.href.split('?');}
if(str[1]){var qstr={};str=str[1].split('&');if(str.length){for(var i=0;i<str.length;i++){var part=str[i].split('=');if(part[0].indexOf('[')!=-1){if(part[0].indexOf('[]')!=-1){var arr=part[0].substring(0,part[0].length-2);if(!qstr[arr]){qstr[arr]=[];}
qstr[arr][qstr[arr].length]=part[1];}else{var arr=part[0].substring(0,part[0].indexOf('['));var data=part[0].substring((part[0].indexOf('[')+1),part[0].indexOf(']'));if(!qstr[arr]){qstr[arr]={};}
qstr[arr][data]=part[1];}}else{qstr[part[0]]=part[1];}}}else{return false;}}else{return false;}
return qstr;}
YAHOO.tools=YAHOO.Tools;YAHOO.TOOLS=YAHOO.Tools;YAHOO.util.Dom.create=YAHOO.Tools.create;$A=YAHOO.util.Anim;$E=YAHOO.util.Event;$D=YAHOO.util.Dom;$T=YAHOO.Tools;$=YAHOO.util.Dom.get;$$=YAHOO.util.Dom.getElementsByClassName;
var txt='Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas sit amet metus. Nunc quam elit, posuere nec, auctor in, rhoncus quis, dui. Aliquam erat volutpat. Ut dignissim, massa sit amet dignissim cursus, quam lacus feugiat.';YAHOO.CSSGridBuilder=function(){}
YAHOO.CSSGridBuilder.init=function(){this.headerStr='YUI: CSS Grid Builder';this.footerStr='Footer is here.';this.headerDefault=this.headerStr;this.footerDefault=this.footerStr;this.type='yui-t7';this.docType='doc';this.rows=[];this.rows[0]=$('splitBody0');this.storeCode=false;this.sliderData=false;this.bd=$('bd');this.doc=$('doc');this.template=$('which_grid');$E.addListener(this.template,'change',YAHOO.CSSGridBuilder.changeType,YAHOO.CSSGridBuilder,true);$E.addListener('show_code','click',YAHOO.CSSGridBuilder.showCode,YAHOO.CSSGridBuilder,true);$E.addListener('setHeader','click',YAHOO.CSSGridBuilder.setHeader,YAHOO.CSSGridBuilder,true);$E.addListener('setFooter','click',YAHOO.CSSGridBuilder.setFooter,YAHOO.CSSGridBuilder,true);$E.addListener('splitBody0','change',YAHOO.CSSGridBuilder.splitBody,YAHOO.CSSGridBuilder,true);$E.addListener('which_doc','change',YAHOO.CSSGridBuilder.changeDoc,YAHOO.CSSGridBuilder,true);$E.addListener('addRow','click',YAHOO.CSSGridBuilder.addRow,YAHOO.CSSGridBuilder,true);$E.addListener('resetBuilder','click',YAHOO.CSSGridBuilder.reset,YAHOO.CSSGridBuilder,true);$E.addListener('about','click',YAHOO.CSSGridBuilder.about,YAHOO.CSSGridBuilder,true);$E.addListener(this.bd,'mouseover',YAHOO.CSSGridBuilder.mouseOver,YAHOO.CSSGridBuilder,true);this.tooltip=new YAHOO.widget.Tooltip('classPath',{context:'bd',showDelay:500});}
YAHOO.CSSGridBuilder.about=function(ev){showAbout=new YAHOO.widget.Dialog('showAbout',{close:true,modal:true,visible:true,fixedcenter:true,height:'250px',width:'250px',zindex:9001});showAbout.setHeader('CSSGridBuilder About');content='<p>Written by Dav Glass &lt;dav.glass@yahoo.com&gt;</p>';content+='<p><a href="http://blog.davglass.com/">blog.davglass.com</a></p>';content+='<p>The Grids Builder is designed to work with the Yahoo User Interface (YUI)  CSS Grids tools. They are freely available and you can download a copy from their developer site here:<br><a href="http://developer.yahoo.com/yui/grids" target="_blank">http://developer.yahoo.com/yui/grids</a></p>';showAbout.setBody('<b>CSS Grid Builder v 0.5</b>'+content);showAbout.render(document.body);$E.stopEvent(ev);}
YAHOO.CSSGridBuilder.reset=function(ev){for(var i=1;i<this.rows.length;i++){if(this.rows[i]){if($('splitBody'+i)){$('splitBody'+i).parentNode.parentNode.removeChild($('splitBody'+i).parentNode);}}}
this.rows=[];this.rows[0]=$('splitBody0');$('which_doc').options.selectedIndex=0;$('which_grid').options.selectedIndex=0;$('splitBody0').options.selectedIndex=0;$('hd').innerHTML='<h1>'+this.headerDefault+'</h1>';$('ft').innerHTML=this.footerDefault;this.headerStr=this.headerDefault;this.footerStr=this.footerDefault;this.changeDoc();this.changeType();this.splitBody();$E.stopEvent(ev);}
YAHOO.CSSGridBuilder.addRow=function(ev){var tmp=$('splitBody0').cloneNode(true);tmp.id='splitBody'+this.rows.length;this.rows[this.rows.length]=tmp;this.rowCounter++;var p=$T.create('p','Row:',[$T.create('a',{href:'#',id:'gridRowDel'+this.rows.length,title:'Remove this row',style:'color: red;'},'[X]'),$T.create('br'),tmp]);$('splitBody0').parentNode.parentNode.appendChild(p);$E.addListener(tmp,'change',YAHOO.CSSGridBuilder.splitBody,YAHOO.CSSGridBuilder,true);$E.addListener('gridRowDel'+this.rows.length,'click',YAHOO.CSSGridBuilder.delRow,YAHOO.CSSGridBuilder,true);this.splitBody();$E.stopEvent(ev);}
YAHOO.CSSGridBuilder.delRow=function(ev){var tar=$E.getTarget(ev);var id=tar.id.replace('gridRowDel','');$('splitBody0').parentNode.parentNode.removeChild(tar.parentNode);this.rows[id]=false;this.splitBody();$E.stopEvent(ev);}
YAHOO.CSSGridBuilder.changeCustomDoc=function(ev){var tar=$E.getTarget(ev);docType=$('which_doc').options[$('which_doc').selectedIndex].value;$E.stopEvent(ev);}
YAHOO.CSSGridBuilder.changeDoc=function(ev){this.docType=$('which_doc').options[$('which_doc').selectedIndex].value;if(this.docType=='custom-doc'){this.showSlider();}else{this.doc.style.width='';this.doc.style.minWidth='';this.sliderData=false;this.doc.id=this.docType;this.doTemplate();}
if(ev){$E.stopEvent(ev);}}
YAHOO.CSSGridBuilder.changeType=function(){this.type=this.template.options[this.template.selectedIndex].value;this.doc.className=this.type;this.doTemplate();}
YAHOO.CSSGridBuilder.doTemplate=function(){if(this.storeCode){this.splitBody();}
var html='';var str='<p>'+$T.stringRepeat(txt,3)+'</p>';var navStr='<p>Navigation Pane</p>';if(this.storeCode){str='<!-- YOUR DATA GOES HERE -->';navStr='<!-- YOUR NAVIGATION GOES HERE -->';}
if(this.bodySplit){if(this.storeCode){str=$T.printf(this.bodySplit,"\t"+'<!-- YOUR DATA GOES HERE -->'+"\n\t");}else{str=$T.printf(this.bodySplit,'<p>'+txt+'</p>');}}
switch(this.type){case'yui-t7':html=str;break;default:html='<div id="yui-main">'+"\n\t"+'<div class="yui-b">'+str+'</div>'+"\n\t"+'</div>'+"\n\t"+'<div class="yui-b">'+navStr+'</div>'+"\n\t";break;}
if(this.storeCode){return html;}else{this.bd.innerHTML=html;}}
YAHOO.CSSGridBuilder.getCode=function(){this.storeCode=true;var css=false;if(this.sliderData){if(this.sliderData.indexOf('px')!=-1){var css='#custom-doc { '+$T.PixelToEmStyle(parseInt(this.sliderData))+' margin:auto; text-align:left; }';}else{var css='#custom-doc { width: '+this.sliderData+'; min-width: 250px; }';}}
code='<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"'+"\n"+' "http://www.w3.org/TR/html4/strict.dtd">'+"\n";code+='<html>'+"\n";code+='<head>'+"\n";code+='   <title>YUI Base Page</title>'+"\n";code+='   <!-- The Grids Builder is designed to work with -->'+"\n";code+='   <!-- the Yahoo User Interface (YUI) CSS Grids tools. -->'+"\n";code+='   <!-- They are freely available and you can download a copy from -->'+"\n";code+='   <!-- their developer site here: http://developer.yahoo.com/yui/grids -->'+"\n";code+='   <!-- THESE PATHS NEED TO BE CHANGED -->'+"\n";code+='   <link rel="stylesheet" href="reset-min.css" type="text/css">'+"\n";code+='   <link rel="stylesheet" href="fonts-min.css" type="text/css">'+"\n";code+='   <link rel="stylesheet" href="grids-min.css" type="text/css">'+"\n";if(css){code+='   <style type="text/css">'+"\n";code+='   '+css+"\n";code+='   </style>'+"\n";}
code+='</head>'+"\n";code+='<body>'+"\n";code+='<div id="'+this.docType+'" class="'+this.type+'">'+"\n";code+='   <div id="hd"><h1>'+this.headerStr+'</h1></div>'+"\n";code+='   <div id="bd">'+"\n\t"+this.doTemplate(true)+"\n\t"+'</div>'+"\n";code+='   <div id="ft">'+this.footerStr+'</div>'+"\n";code+='</div>'+"\n";code+='</body>'+"\n";code+='</html>'+"\n";this.storeCode=false;return code;}
YAHOO.CSSGridBuilder.showCode=function(ev){code=this.getCode();showCode=new YAHOO.widget.Dialog('showCode',{close:true,modal:true,visible:true,fixedcenter:true,height:'450px',width:'650px',zindex:9001});showCode.setHeader('CSSGridBuilder Code');showCode.setBody('<textarea style="height: 300px; width: 99%;" name="code" class="HTML">'+code+'</textarea>');showCode.render(document.body);dp.SyntaxHighlighter.HighlightAll('code');$E.stopEvent(ev);}
YAHOO.CSSGridBuilder.setHeader=function(ev){var str=prompt('Set header value to: ',this.headerStr);if(str!=null){this.headerStr=str;$('hd').innerHTML='<h1>'+str+'</h1>';}
$E.stopEvent(ev);}
YAHOO.CSSGridBuilder.setFooter=function(ev){var str=prompt('Set footer value to: ',this.footerStr);if(str!=null){this.footerStr=str;$('ft').innerHTML=str;}
$E.stopEvent(ev);}
YAHOO.CSSGridBuilder.splitBody=function(){this.bodySplit='';for(var i=0;i<this.rows.length;i++){this.splitBodyTemplate($('splitBody'+i));}
if(!this.storeCode){this.doTemplate();}}
YAHOO.CSSGridBuilder.splitBodyTemplate=function(tar){if(tar){var bSplit=tar.options[tar.selectedIndex].value;var str='';switch(bSplit){case'1':str+='<div class="yui-g">'+"\n";str+='{0}';str+='</div>'+"\n";break;case'2':str+='<div class="yui-g">'+"\n";str+='    <div class="yui-u first">'+"\n";str+='{0}';str+='    </div>'+"\n";str+='    <div class="yui-u">'+"\n";str+='{0}';str+='    </div>'+"\n";str+='</div>'+"\n";break;case'3':str+='<div class="yui-g">'+"\n";str+='    <div class="yui-gb first">'+"\n";str+='        <div class="yui-u first">'+"\n";str+='{0}';str+='        </div>'+"\n";str+='        <div class="yui-u">'+"\n";str+='{0}';str+='        </div>'+"\n";str+='        <div class="yui-u">'+"\n";str+='{0}';str+='        </div>'+"\n";str+='    </div>'+"\n";str+='</div>'+"\n";break;case'4':str+='<div class="yui-g">'+"\n";str+='    <div class="yui-g first">'+"\n";str+='        <div class="yui-u first">'+"\n";str+='{0}';str+='        </div>'+"\n";str+='        <div class="yui-u">'+"\n";str+='{0}';str+='        </div>'+"\n";str+='    </div>'+"\n";str+='    <div class="yui-g">'+"\n";str+='        <div class="yui-u first">'+"\n";str+='{0}';str+='        </div>'+"\n";str+='        <div class="yui-u">'+"\n";str+='{0}';str+='        </div>'+"\n";str+='    </div>'+"\n";str+='</div>'+"\n";break;case'5':str+='<div class="yui-g">'+"\n";str+='    <div class="yui-u first">'+"\n";str+='{0}';str+='    </div>'+"\n";str+='    <div class="yui-g">'+"\n";str+='        <div class="yui-u first">'+"\n";str+='{0}';str+='        </div>'+"\n";str+='        <div class="yui-u">'+"\n";str+='{0}';str+='        </div>'+"\n";str+='    </div>'+"\n";str+='</div>'+"\n";break;case'6':str+='<div class="yui-g">'+"\n";str+='    <div class="yui-g first">'+"\n";str+='        <div class="yui-u first">'+"\n";str+='{0}';str+='        </div>'+"\n";str+='        <div class="yui-u">'+"\n";str+='{0}';str+='        </div>'+"\n";str+='    </div>'+"\n";str+='    <div class="yui-u">'+"\n";str+='{0}';str+='    </div>'+"\n";str+='</div>'+"\n";break;case'7':str+='<div class="yui-gc">'+"\n";str+='    <div class="yui-u first">'+"\n";str+='{0}';str+='    </div>'+"\n";str+='    <div class="yui-u">'+"\n";str+='{0}';str+='    </div>'+"\n";str+='</div>'+"\n";break;case'8':str+='<div class="yui-gd">'+"\n";str+='    <div class="yui-u first">'+"\n";str+='{0}';str+='    </div>'+"\n";str+='    <div class="yui-u">'+"\n";str+='{0}';str+='    </div>'+"\n";str+='</div>'+"\n";break;case'9':str+='<div class="yui-ge">'+"\n";str+='    <div class="yui-u first">'+"\n";str+='{0}';str+='    </div>'+"\n";str+='    <div class="yui-u">'+"\n";str+='{0}';str+='    </div>'+"\n";str+='</div>'+"\n";break;case'10':str+='<div class="yui-gf">'+"\n";str+='    <div class="yui-u first">'+"\n";str+='{0}';str+='    </div>'+"\n";str+='    <div class="yui-u">'+"\n";str+='{0}';str+='    </div>'+"\n";str+='</div>'+"\n";break;}
if(!this.storeCode){this.bodySplit+='<div id="gridBuilder'+(this.rows.length-1)+'">'+str+'</div>';}else{this.bodySplit+=str;}}}
YAHOO.CSSGridBuilder.mouseOver=function(ev){var elm=$E.getTarget(ev);var path=[];var new_path=[];cont=true;while(cont){if(elm.className){path[path.length]=elm.className;}
if(elm.parentNode){elm=elm.parentNode;}else{cont=false;}}
for(var i=(path.length-1);i>=0;i--){new_path[new_path.length]=path[i];}
this.bd.title='#'+this.docType+': '+new_path.join(' :  ');}
YAHOO.CSSGridBuilder.showSlider=function(){showSlider=new YAHOO.widget.Dialog('showSlider',{close:true,dragable:false,modal:true,visible:true,fixedcenter:true,width:'275px',zindex:9001,postmethod:'none'});showSlider.setHeader('CSSGridBuilder Custom Body Size');var body='<p>Adjust the slider below to adjust your body size or set it manually with the text input. <i>(Be sure to include the % or px in the text input)</i></p>';body+='<form name="customBodyForm" method="POST" action="">';body+='<p>Current Setting: <input type="text" id="sliderValue" value="100%" size="8" onfocus="this.select()" /></p>';body+='<span>Unit: ';body+='<input type="radio" name="movetype" id="moveTypePercent" value="percent" checked> <label for="moveTypePercent">Percent</label>&nbsp;';body+='<input type="radio" name="movetype" id="moveTypePixel" value="pixel"> <label for="moveTypePixel">Pixel</label></span>';body+='</form>';body+='<div id="sliderbg"><div id="sliderthumb"><img src="http://developer.yahoo.com/yui/examples/slider/img/horizSlider.png" /></div>';body+='</div>';showSlider.setBody(body);var handleCancel=function(){showSlider.hide();return false;}
var handleSubmit=function(){YAHOO.CSSGridBuilder.sliderData=$('sliderValue').value;showSlider.hide();}
var myButtons=[{text:'Save',handler:handleSubmit,isDefault:true},{text:'Cancel',handler:handleCancel}];var handleChange=function(f){if(typeof f=='object'){f=slider.getValue();}
if($('moveTypePercent').checked){var w=Math.round(f/2);$('custom-doc').style.width=w+'%';$('sliderValue').value=w+'%';}else{var w=Math.round(f/2);var pix=Math.round($D.getViewportWidth()*(w/100));$('custom-doc').style.width=pix+'px';$('sliderValue').value=pix+'px';}
$('custom-doc').style.minWidth='250px';}
var handleBlur=function(){f=$('sliderValue').value;if(f.indexOf('%')!=-1){$('moveTypePercent').checked=true;f=(parseInt(f)*2);}else if(f.indexOf('px')!=-1){$('moveTypePixel').checked=true;f=(((parseInt(f)/$D.getViewportWidth())*100)*2);}else{$('sliderValue').value='100%';f=200;}
slider.setValue(f);}
showSlider.cfg.queueProperty("buttons",myButtons);showSlider.render(document.body);slider=YAHOO.widget.Slider.getHorizSlider('sliderbg','sliderthumb',0,200,1);slider.setValue(200);slider.onChange=handleChange;$E.addListener(['moveTypePercent','moveTypePixel'],'click',handleChange);$E.addListener('sliderValue','blur',handleBlur);this.doc.id=this.docType;this.doc.style.width='100%';this.doTemplate();}